---
title: "Analyses"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'C:/Users/gabouland/Documents/004 PhD/008scBinaryAnalysis/Manuscript/Organized/')
```

# Packages

```{r}
library(reshape2)
library(ggplot2)
library(magrittr)
library(ggridges)
library(patchwork)
library(clusterProfiler)
library(org.Hs.eg.db)
library(BiocGenerics)
library(ggVennDiagram)
```

# Dataset and test statistics (Fig 1a)

```{r}
completeStats <- readRDS("./004 Results/completeStats_fig1a2.rds")
completeStats$dataset <- rownames(completeStats)
datachars <- c("zeroPct","N_individuals_ct","N_individuals_case",
               "No.cells_ct","No.cells_case","N_subpopulations","N_genes","N_cells",
               "pct.agree","cor")
testStatistics <- c("N_total_tested", "N_total_sign","N_common_sign","N_DD_sign","N_wilcox_sign")
significantStatisticsUniques <- c("N_DD_unique_sign","N_wilcox_unique_sign")
datacharsScaled <- apply(completeStats[,datachars],2,scale) %>% as.data.frame()
rownames(datacharsScaled) <- rownames(completeStats)
testStatisticsScaled <- apply(completeStats[,testStatistics],1,scale) %>% as.data.frame() %>% t()
colnames(testStatisticsScaled) <- testStatistics
significantStatisticsUniquesScaled <- apply(completeStats[,significantStatisticsUniques],1,scale) %>% as.data.frame() %>% t()
colnames(significantStatisticsUniquesScaled) <- significantStatisticsUniques
scaled <- cbind(datacharsScaled,testStatisticsScaled,significantStatisticsUniquesScaled)
scaled$dataset <- rownames(completeStats)
moltenReal <- melt(completeStats[,colnames(scaled)],id.vars = "dataset")
molten <- melt(scaled,id.vars = "dataset")
molten$realValue <- moltenReal$value

ggplot(molten,aes(variable,dataset, fill = value)) + geom_tile() +
  viridis::scale_fill_viridis(option = "D",direction = 1) + theme_minimal() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) + geom_text(col = "grey",aes(label = round(realValue, 2)))

```

# Linear association between effect size estimates (Fig 1b)

```{r}
nothreshDat <- readRDS(file = "./004 Results/DDA_DEA_results_all_datasets.rds")

#Correlation between log OR and log FC per dataset
logOR_logFC_correlation <- lapply(nothreshDat,function(both){
  R <- cor.test(both$DD$Estimate,both$wilcox$avg_logFC)$estimate
  P <- cor.test(both$DD$Estimate,both$wilcox$avg_logFC)$p.value
  c(R,P)
}) %>% do.call(what = rbind)
colnames(logOR_logFC_correlation) <- c("r","p")
logOR_logFC_correlation <- as.data.frame(logOR_logFC_correlation)
summary(logOR_logFC_correlation$r)

##Scale difference between logOR AND logFC
Scale_diff <- lapply(nothreshDat,function(both){
  res <- lm(both$DD$Estimate ~ both$wilcox$avg_logFC)
  summary(res)$coefficients[2,1]
}) %>% unlist()

logOR_logFC_correlation$scalediff <- Scale_diff
logOR_logFC_linear_association <- logOR_logFC_correlation

saveRDS(logOR_logFC_linear_association,file = "./004 Results/logOR_logFC_linear_association.rds" )

## Cancer atlas (2) example
DD <- nothreshDat$cancerAtlas_naive_vs_transitional_tcells$DD
will <- nothreshDat$cancerAtlas_naive_vs_transitional_tcells$wilcox
plotData <- data.frame(DD$Estimate, will$avg_logFC)
ggplot(plotData,aes(will.avg_logFC,DD.Estimate)) + geom_point() + geom_smooth(method = "lm") + theme_minimal() + xlim(-2,2) + ylim(-2,2)

```

# Extreme DDGs-only and DEGs-only (Fig 1c, Fig 1d)

```{r}
source("./002 Scripts/generateDataIndepth.R")
dir <- c("./003 Data/Summary")
files <-  list.files(dir)
summ <- lapply(files,function(x)readRDS(sprintf("%s/%s",dir,x)))
names(summ) <- gsub(".rds","",files)
all <- lapply(names(summ),function(x){
                tmpData <- generateDataIndepth(nothreshDat,summ,x)
                tmpData$dataset <- as.character(x)
                tmpData
      }) %>% do.call(what = "rbind")
all <- all[all$set %in% c("DD only","Wil only", "common"),]



all <- all[order(all$P_delta,decreasing = T),]
all <- all[!is.infinite(all$P_delta),]
all[all$set == "DD only" & all$dataset == "mouseDroplet" ,]

nothreshDat$mouseDroplet$DD["Rpl5",]
nothreshDat$mouseDroplet$wilcox["Rpl5",]
```



```{r}
Rpl5 <- readRDS("./003 Data/Extreme_DDG_DEG_only_examples/Rpl5_Rps15_mouse_droplet.rds")

p1 <- ggplot(Rpl5,aes(y= status,x = Rpl5, fill = status)) + geom_density_ridges(
    quantile_lines = TRUE, scale = 0.9,
    vline_size = 1, vline_color = "black", quantiles = 2,
    alpha = .5 
  ) + theme_minimal() + scale_fill_manual(values=c("#56B4E9", "#009E73")) + theme(legend.position = "top")

p1

p2 <- ggplot(Rpl5,aes(y= status,x = Rps15, fill = status)) + geom_density_ridges(
    quantile_lines = TRUE, scale = 0.9,
    vline_size = 1, vline_color = "black", quantiles = 2,
    alpha = .5 
  ) + theme_minimal() + scale_fill_manual(values=c("#56B4E9", "#009E73")) + theme(legend.position = "top")

p1 + p2
```

# Recurring genes (Sfig 2)

```{r}
all <- all[!all$dataset %in% c("mouseDroplet","mouseFACS"),]
DD_only <- all[all$set == "DD only",]
plotData <- data.frame(table(DD_only$gene) %>% table())
plotData$N <- plotData$.
DDPlot <- ggplot(plotData,aes(N,Freq)) + geom_bar(stat = "identity") +
  geom_text(aes(N,Freq,label=sprintf("No. Genes: %s",Freq))) + 
  scale_y_log10() + theme_minimal() + labs(x = "No. datasets") + labs(title = "a") + theme(plot.title = element_text(size=25))

Wil_only <- all[all$set == "Wil only",]
plotData <- data.frame(table(Wil_only$gene) %>% table())
plotData$N <- plotData$.

WilPlot <- ggplot(plotData,aes(N,Freq)) + geom_bar(stat = "identity") +
  geom_text(aes(N,Freq,label=sprintf("No. Genes: %s",Freq))) + 
  scale_y_log10() + theme_minimal() + labs(x = "No. datasets") +  labs(title = "b") + theme(plot.title = element_text(size=25))

DDPlot + WilPlot
```

# GO term enrichment

```{r}
translationTable <- toTable(org.Hs.egSYMBOL)
allDD_only <- all[all$set == "DD only",c("gene","dataset")]#`Wil only` for DEA#
colnames(allDD_only) <- c("values","ind")
allDD_only$values <- as.factor(allDD_only$values)
allDD_only$ind <- as.factor(allDD_only$ind)
allDD_only$entrez <- translationTable[match(allDD_only$values,translationTable$symbol),"gene_id"]
res <- clusterProfiler::enrichGO(gene = allDD_only$entrez, OrgDb = "org.Hs.eg.db", pvalueCutoff = 1,ont = "BP")
sign <- res@result[res@result$p.adjust <= 0.05,]
Ndatasets <- lapply(sign$geneID,function(genes){
  genes <- unlist(strsplit(x = genes,split = "/"))
  sets <- allDD_only[allDD_only$entrez %in% genes,]
  return(table(sets$ind))
}) %>% do.call(what = rbind)
rownames(Ndatasets) <- sign$ID
Ndatasets<- melt(Ndatasets)
Ndatasets$P <- sign[match(Ndatasets$Var1,sign$ID),"pvalue"]
Ndatasets$desc <- sign[match(Ndatasets$Var1,sign$ID),"Description"]
Ndatasets <- Ndatasets[Ndatasets$value != 0,]
ALL <- names(table(Ndatasets$Var1))[table(Ndatasets$Var1)==14]
Ndatasets$all <- ifelse(Ndatasets$Var1 %in% ALL,1,0) %>% as.factor()
Ndatasets$desc <- factor(Ndatasets$desc, levels = table(Ndatasets$desc) %>% sort(decreasing = T) %>% names())
Ndatasets$Var1 <- factor(Ndatasets$Var1, levels = table(Ndatasets$Var1) %>% sort(decreasing = T) %>% names())
Ndatasets[Ndatasets$Var1 %in% ALL,"desc"] %>% unique()
res@result <- res@result[res@result$ID %in% allGOs,]

##SAVE results
saveRDS(res@result,file="./004 Results/DDG_only_raw_GOenrichment.rds")
write.csv2(res@result[res@result$ID %in% allGOs,], file = "./001 Manuscript/Supplementary/STable2.csv")
b <- ggplot(Ndatasets,aes(x = Var2, Var1, size = value,col = all)) + geom_point() + theme_minimal() + scale_color_manual(values=c("red","blue")) + coord_flip()
allGOs <- Ndatasets[Ndatasets$all ==1,"Var1"] %>% as.character() %>% unique()
clusterProfiler::emapplot(res)
a + b
plotly::ggplotly(b)
```

## Validation in bulk (Fig 2 and SFig 3)

```{r}
DD <- nothreshDat$AD$DD
wil <- nothreshDat$AD$wilcox
tested_genes <- rownames(DD)


## Hokama ##
AD_bulk <- rio::import("./003 Data/Bulk/6234_GSE36980_expmat.data.txt")
exp <- AD_bulk[,grepl("Symbol",colnames(AD_bulk))| grepl("GSE36980",colnames(AD_bulk))]
rownames(exp) <- make.unique(exp$GeneSymbol)
exp$GeneSymbol <- NULL
exp <- exp[rownames(exp) %in% tested_genes,]
samplesheet <- data.frame("IDs" = colnames(exp),
                          "status" = ifelse(grepl("non.AD",colnames(exp)),"Control","AD"))
index <- which(samplesheet$status == "AD")
##END##

## Friedman ##
AD_bulk <- rio::import("./003 Data/Bulk/15650_GSE95587_expmat.data.txt")
exp <- AD_bulk[,grepl("Symbol",colnames(AD_bulk))| grepl("GSE95587",colnames(AD_bulk))]
rownames(exp) <- make.unique(exp$GeneSymbol)
exp$GeneSymbol <- NULL
exp <- exp[rownames(exp) %in% tested_genes,]
samplesheet <- data.frame("IDs" = colnames(exp),
                          "status" = ifelse(grepl("CON",colnames(exp)),"Control","AD"))
index <- which(samplesheet$status == "AD")
##END##


wilcox_P <- sapply(rownames(exp),function(gene){
  min(2 * min(limma::rankSumTestWithCorrelation(index = index, statistics = exp[gene,])), 1)
})
avgFC <- sapply(rownames(exp),function(gene){
  log(rowMeans(exp[gene,index],na.rm = T)/ rowMeans(exp[gene,!1:ncol(exp) %in% index],na.rm = T))
})

bulk <- data.frame("P" = wilcox_P, "FC" = avgFC)
bulk$fdr <- p.adjust(bulk$P,method = "fdr")

DD <- DD[rownames(bulk),]
wil <- wil[rownames(bulk),]
vennData <- list("bulk" = rownames(bulk[bulk$fdr<=0.05,]),
     "DDA" = rownames(DD[DD$fdr<=0.05,]),
     "DEA" = rownames(wil[wil$fdr<=0.05,]))
venn <- ggVennDiagram(vennData)
plotData <- data.frame(bulk$FC, DD$Estimate,wil$avg_logFC)
a <- ggplot(plotData,aes(bulk.FC,DD.Estimate)) + geom_point() + geom_smooth(method="lm") + geom_hline(yintercept = 0) + geom_vline(xintercept = 0) + theme_minimal() + ylim(-4,4) + xlim(-0.50,0.50)
b <- ggplot(plotData,aes(bulk.FC,wil.avg_logFC)) + geom_point() + geom_smooth(method="lm") + geom_hline(yintercept = 0) + geom_vline(xintercept = 0) + theme_minimal() + ylim(-2.5,2.5) + xlim(-0.50,0.50)
x<- cor.test(plotData$bulk.FC,plotData$wil.avg_logFC,method = "pearson")
x$estimate
x$p.value
venn | a / b
```

## Different binary thresholds

```{r}
library(magrittr)
library(reshape2)
thresh <- readRDS("./004 Results/DDA_different_binary_thresholds.rds")

#Plot correlation with wilcox
wil <- nothreshDat$AD$wilcox
plot_cor <- function(wil,DD){
  common <- intersect(rownames(wil),rownames(DD))
  plotData <- data.frame("logFC" = wil[common,"avg_logFC"],
                         "logOR" = DD[common,"Estimate"])
  return(cor.test(plotData$logFC,plotData$logOR,method = "pearson")$estimate)
}
cors <- lapply(1:10,function(i){plot_cor(wil,thresh[[i]])}) %>% do.call(what = rbind) %>% as.data.frame()
cors$thresh <- 1:10
cor_plot <- ggplot(cors,aes(thresh,rho)) + geom_point() + geom_line() +
  scale_x_discrete(limits=as.character(1:10)) + theme(plot.title = element_text(size=25)) + labs(title = "c")
##End##

res <- lapply(thresh,function(single){
  N_tested <- nrow(single)
  N_sign <- nrow(single[single$fdr<=0.05,])
  c(N_tested,N_sign)
}) %>% do.call(what = rbind) %>% as.data.frame()

res$threhold <- seq(1:10)
colnames(res) <- c("tested","significant","threshold")


significant_plot <- ggplot(res,aes(threshold,significant)) + geom_bar(stat = "identity") +
  scale_x_discrete(limits=as.character(1:10)) + theme(plot.title = element_text(size=25))+ labs(title = "b")

tested_plot <- ggplot(res,aes(threshold,tested)) + geom_bar(stat = "identity") +
  scale_x_discrete(limits=as.character(1:10))+ theme(plot.title = element_text(size=25)) + labs(title = "a")


res$tested <- res$tested - res$significant
molten <- melt(res,id.vars = "threshold")

ggplot(molten,aes(threshold,value,fill = variable)) + geom_bar(stat = "identity") + scale_x_discrete(limits=as.character(1:10)) +
  theme(plot.title = element_text(size=25)) + theme_minimal() + scale_fill_manual(values = c("#046C9A","#D69C4E"))


vennData <- list("One" = rownames(thresh[[1]][thresh[[1]]$fdr<=0.05,]),
                 "Two" = rownames(thresh[[2]][thresh[[2]]$fdr<=0.05,]),
     "Five" = rownames(thresh[[5]][thresh[[5]]$fdr<=0.05,]),
     "Wilcox" = rownames(wil[wil$fdr<=0.05,]))
venn <- ggVennDiagram(vennData) +  theme(plot.title = element_text(size=25)) + labs(title = "d")

(tested_plot) | (significant_plot) / (cor_plot) | (venn)
```

